// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzwNkQ8E-Y94IGxF5rklYECpnQ2JPfTzM',
    appId: '1:1005078907751:web:3a003750196724861dbdc2',
    messagingSenderId: '1005078907751',
    projectId: 'pos-system-9d8ac',
    authDomain: 'pos-system-9d8ac.firebaseapp.com',
    storageBucket: 'pos-system-9d8ac.firebasestorage.app',
    measurementId: 'G-8FYHPBYVEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-JJgpQvTPs2NN_9sAfcRhP4ec4TAcxA0',
    appId: '1:1005078907751:android:560791ec848b3a541dbdc2',
    messagingSenderId: '1005078907751',
    projectId: 'pos-system-9d8ac',
    storageBucket: 'pos-system-9d8ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiAq3szOOWq7eX9LkcsPXb7iAVucVZneA',
    appId: '1:1005078907751:ios:35191c785f8da4df1dbdc2',
    messagingSenderId: '1005078907751',
    projectId: 'pos-system-9d8ac',
    storageBucket: 'pos-system-9d8ac.firebasestorage.app',
    iosBundleId: 'com.example.posSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiAq3szOOWq7eX9LkcsPXb7iAVucVZneA',
    appId: '1:1005078907751:ios:35191c785f8da4df1dbdc2',
    messagingSenderId: '1005078907751',
    projectId: 'pos-system-9d8ac',
    storageBucket: 'pos-system-9d8ac.firebasestorage.app',
    iosBundleId: 'com.example.posSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzwNkQ8E-Y94IGxF5rklYECpnQ2JPfTzM',
    appId: '1:1005078907751:web:3a003750196724861dbdc2',
    messagingSenderId: '1005078907751',
    projectId: 'pos-system-9d8ac',
    authDomain: 'pos-system-9d8ac.firebaseapp.com',
    storageBucket: 'pos-system-9d8ac.firebasestorage.app',
    measurementId: 'G-8FYHPBYVEY',
  );

}